const mockProducts = [
  {
    id: 1,
    title: "Samsung Galaxy A52",
    brand: "Samsung",
    price: 220,
    ram: "6GB",
    memory: "128GB",
    year: 2023,
    thumbnail: "/img/samsung1.jpg",
    description: "O'rtacha byudjet uchun mo'ljallangan kuchli telefon. AMOLED ekran, yaxshi kamera.",
    downside: "Plastik korpus, tez qizishi mumkin."
  },
  {
    id: 2,
    title: "Redmi Note 11",
    brand: "Redmi",
    price: 180,
    ram: "4GB",
    memory: "64GB",
    year: 2022,
    thumbnail: "/img/redmi1.jpg",
    description: "Yaxshi dizayn va kuchli batareya bilan keladi. AMOLED displey va stereo karnaylar.",
    downside: "64GB xotira tez to‘lishi mumkin."
  },
  {
    id: 3,
    title: "iPhone 12",
    brand: "iPhone",
    price: 600,
    ram: "4GB",
    memory: "128GB",
    year: 2021,
    thumbnail: "/img/iphone1.jpg",
    description: "Flagship iPhone modeli. Kuchli A14 chip, 5G qo‘llab-quvvatlaydi.",
    downside: "Zaryadlovchi adapter qutiga qo‘shilmagan."
  },
  {
    id: 4,
    title: "Poco X4 Pro",
    brand: "Poco",
    price: 250,
    ram: "8GB",
    memory: "128GB",
    year: 2023,
    thumbnail: "/img/poco1.jpg",
    description: "Tez ishlaydigan ekran va katta batareyaga ega. Narxiga nisbatan yaxshi imkoniyatlar.",
    downside: "Kamerasi sust bo‘lishi mumkin."
  },
  {
    id: 5,
    title: "Vivo Y21",
    brand: "Vivo",
    price: 160,
    ram: "4GB",
    memory: "64GB",
    year: 2022,
    thumbnail: "/img/vivo1.jpg",
    description: "Oddiy kundalik foydalanish uchun qulay model.",
    downside: "Pastroq ekran piksellari va sekin protsessor."
  },
  {
    id: 6,
    title: "Samsung Galaxy S21",
    brand: "Samsung",
    price: 500,
    ram: "8GB",
    memory: "256GB",
    year: 2021,
    thumbnail: "/img/samsung2.jpg",
    description: "Flagship model, kuchli kamera tizimi va ishlash tezligi bilan ajralib turadi.",
    downside: "Batareya uzoq vaqt yetmasligi mumkin."
  },
  {
    id: 7,
    title: "Redmi Note 12 Pro",
    brand: "Redmi",
    price: 300,
    ram: "6GB",
    memory: "128GB",
    year: 2024,
    thumbnail: "/img/redmi2.jpg",
    description: "Yangi dizayn va 5G qo‘llab-quvvatlovi bilan bozorni zabt etmoqda.",
    downside: "Yorug‘likda kamerasi biroz sust ishlaydi."
  },
  {
    id: 8,
    title: "iPhone 13 Mini",
    brand: "iPhone",
    price: 650,
    ram: "4GB",
    memory: "128GB",
    year: 2022,
    thumbnail: "/img/iphone2.jpg",
    description: "Compact dizayn, flagship kuch bilan. Qo‘lda tutish qulay.",
    downside: "Kichik ekran ba'zilar uchun noqulay bo‘lishi mumkin."
  },
  {
    id: 9,
    title: "Poco F4",
    brand: "Poco",
    price: 320,
    ram: "8GB",
    memory: "256GB",
    year: 2023,
    thumbnail: "/img/poco2.jpg",
    description: "Yuqori darajadagi ishlash tezligi va narx-nisbati juda yaxshi.",
    downside: "MIUI reklamalar bilan bezovta qilishi mumkin."
  },
  {
    id: 10,
    title: "Vivo V25",
    brand: "Vivo",
    price: 280,
    ram: "8GB",
    memory: "128GB",
    year: 2023,
    thumbnail: "/img/vivo2.jpg",
    description: "Yaxshi kamera va dizayn bilan ajralib turadi.",
    downside: "O‘yinlarda ba’zida lag bo‘lishi mumkin."
  },
  {
    id: 11,
    title: "Samsung Galaxy A14",
    brand: "Samsung",
    price: 170,
    ram: "4GB",
    memory: "64GB",
    year: 2023,
    thumbnail: "/img/samsung3.jpg",
    description: "Yangi foydalanuvchilar uchun byudjet telefon. One UI Core bilan ishlaydi.",
    downside: "Kuchsiz protsessor va o‘rtacha kamera."
  },
  {
    id: 12,
    title: "Redmi 10C",
    brand: "Redmi",
    price: 140,
    ram: "4GB",
    memory: "64GB",
    year: 2022,
    thumbnail: "/img/redmi3.jpg",
    description: "Eng arzon narxdagi telefonlardan biri. Katta ekran.",
    downside: "Displey sifati va kamera o‘rtacha."
  },
  {
    id: 13,
    title: "iPhone SE 2020",
    brand: "iPhone",
    price: 300,
    ram: "3GB",
    memory: "64GB",
    year: 2020,
    thumbnail: "/img/iphone3.jpg",
    description: "Kichik dizayn, kuchli protsessor bilan. Klassik Home tugmasi.",
    downside: "Batareya kichik, kamerasi oddiy."
  },
  {
    id: 14,
    title: "Poco M4 Pro",
    brand: "Poco",
    price: 200,
    ram: "6GB",
    memory: "128GB",
    year: 2022,
    thumbnail: "/img/poco3.jpg",
    description: "Narxiga nisbatan yaxshi ishlash tezligi va ekran sifati.",
    downside: "Plastik korpus va o‘rtacha kamera."
  },
  {
    id: 15,
    title: "Vivo Y33s",
    brand: "Vivo",
    price: 190,
    ram: "8GB",
    memory: "128GB",
    year: 2022,
    thumbnail: "/img/vivo3.jpg",
    description: "Yaxshi kamera, zamonaviy dizayn. Kundalik foydalanish uchun a’lo.",
    downside: "Kamerasi kechasi yaxshi ishlamaydi."
  },
  {
    id: 16,
    title: "Samsung Galaxy M13",
    brand: "Samsung",
    price: 160,
    ram: "4GB",
    memory: "64GB",
    year: 2022,
    thumbnail: "/img/samsung4.jpg",
    description: "Batareyasi kuchli va ekran hajmi katta.",
    downside: "Protsessor sekin, o‘yinlar uchun mos emas."
  },
  {
    id: 17,
    title: "Redmi Note 9 Pro",
    brand: "Redmi",
    price: 170,
    ram: "6GB",
    memory: "128GB",
    year: 2021,
    thumbnail: "/img/redmi4.jpg",
    description: "Yaxshi ishlash tezligi, katta ekran, kuchli batareya.",
    downside: "Og‘ir dizayn va MIUI’da reklama ko‘p."
  },
  {
    id: 18,
    title: "iPhone XR",
    brand: "iPhone",
    price: 400,
    ram: "3GB",
    memory: "64GB",
    year: 2020,
    thumbnail: "/img/iphone4.jpg",
    description: "Katta ekran va Face ID bilan qulaylik yaratadi. iOS tizimi doimiy yangilanadi.",
    downside: "Past pikselli ekran (Liquid Retina)."
  },
  {
    id: 19,
    title: "Poco X3 NFC",
    brand: "Poco",
    price: 230,
    ram: "6GB",
    memory: "128GB",
    year: 2021,
    thumbnail: "/img/poco4.jpg",
    description: "Tez ishlaydigan 120Hz ekran va kuchli batareya.",
    downside: "Qurilma og‘ir va kamera kechasi sust ishlaydi."
  },
  {
    id: 20,
    title: "Vivo Y20",
    brand: "Vivo",
    price: 150,
    ram: "3GB",
    memory: "64GB",
    year: 2021,
    thumbnail: "/img/vivo4.jpg",
    description: "Yoshlar va oddiy foydalanish uchun arzon variant.",
    downside: "Sekin ishlash va eski dizayn."
  }
];

export default mockProducts;
